train_set_path : 'D:\document\paper\personpaper\audio-visual_consistance\data\train\train_high.pkl'
test_set_path : 'D:\document\paper\personpaper\audio-visual_consistance\data\test\test_high.pkl'
store_model_dir : 'D:\document\pycharmproject\AVCDetection\output'
evaluate_path : 'D:\document\pycharmproject\AVCDetection\output\record.txt'


train :
    save_steps : 1
    iters: 100
    loaded_model_num : 5
    loaded_model : True


logger:
    logger_dir : ''
    tag : 'init'
optimizer:
    lr: 0.0035
    beta1: 0.9
    beta2: 0.999
    amsgrad: True
    weight_decay: 0.0003
    grad_norm: 20

loss:
    margin: 700
